testapp/urls.py
"""Define URLs for the test app."""

from django.contrib.auth.models import User
from django.urls import path
from django.views.generic import DetailView, ListView, TemplateView

from . import views
from .models import TestModel, TestModelList, TestModelPK

app_name = "testapp"
urlpatterns = [
    path("", ListView.as_view(model=TestModel), name="testmodels"),
    path("create", views.TestCreateView.as_view(), name="testmodel-add"),
    path("list", ListView.as_view(model=TestModelList), name="testmodellists"),
    path("user/<int:pk>", DetailView.as_view(model=User), name="user"),
    path("pk/<int:pk>", DetailView.as_view(model=TestModelPK), name="testmodelpk"),
    path(
        "settings",
        TemplateView.as_view(template_name="testapp/settings.html"),
        name="settings",
    ),
    path("<slug:slug>", DetailView.as_view(model=TestModel), name="testmodel"),
    path("<slug:slug>/update", views.TestUpdateView.as_view(), name="testmodel-update"),
    path("<slug:slug>/delete", views.TestDeleteView.as_view(), name="testmodel-delete"),
]

testproject/urls.py
"""Main URLS for the test project."""

from django.contrib import admin
from django.contrib.auth import get_user_model
from django.urls import include, path
from django.views.generic import TemplateView

CTX = {
    "email": "test@example.org",
    "phone": "(+33) 1 23 45 67 89",
    "user": get_user_model().objects.first,
    "users": get_user_model().objects.all,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        "",
        TemplateView.as_view(template_name="base.html", extra_context=CTX),
        name="test",
    ),
    path("test/", include("testapp.urls")),
]

testapp/models.py
"""Models for the testapp."""

from django.db import models

from ndh.models import Links, NamedModel, TimeStampedModel


class TestModel(Links, TimeStampedModel, NamedModel):
    """Main test model."""

    tests = models.IntegerField(default=42)
    tests_decimal = models.DecimalField(default=3.14, max_digits=5, decimal_places=2)
    moment = models.DateTimeField()
    datalist = models.CharField(max_length=30)


class TestModelList(TestModel):
    """Test model for get_absolute_url for lists."""

    absolute_url_detail = False


class TestModelPK(Links, TimeStampedModel):
    """Test model for get_absolute_url for objects."""

    pass

testproject/models.py
from enum import IntEnum

from django.db import models
from django.urls import reverse

from ndh.models import Links, NamedModel, TimeStampedModel
from ndh.utils import enum_to_choices


class TestModel(Links, TimeStampedModel, NamedModel):
    YEARS_IN_SCHOOL = IntEnum('years_in_school', 'freshman sophomore junior senior')

    year_in_school = models.IntegerField(choices=enum_to_choices(YEARS_IN_SCHOOL), default=1)
    tests = models.IntegerField(default=42)
    moment = models.DateTimeField()

    def get_absolute_url(self):
        return reverse('detail', args=[self.slug])

testapp/forms.py
"""Forms for the testapp."""

from django.forms import ModelForm

from ndh.forms import AccessibleDateTimeField, DatalistField

from .models import TestModel


def get_datalist():
    """Generate some datalist."""
    return {c * 8: f"Many {c}" for c in "auienrst"}


class TestForm(ModelForm):
    """Form to test ndh.forms."""

    moment = AccessibleDateTimeField()
    datalist = DatalistField(datalist=get_datalist)

    class Meta:
        """ModelForm definitions."""

        model = TestModel
        fields = ("name", "tests", "moment", "datalist")

testapp/views.py
"""Views for testapp."""

from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView

from ndh.mixins import NDHDeleteMixin, NDHFormMixin, SuperUserRequiredMixin

from .forms import TestForm
from .models import TestModel


class TestCreateView(NDHFormMixin, CreateView):
    """View to test NDHFormMixin."""

    model = TestModel
    form_class = TestForm
    title = "Create Test"


class TestUpdateView(NDHFormMixin, UpdateView):
    """View to test NDHFormMixin continue_edit."""

    model = TestModel
    form_class = TestForm
    title = "Update Test"
    continue_edit = True


class TestDeleteView(NDHDeleteMixin, SuperUserRequiredMixin, DeleteView):
    """View to test other mixins."""

    model = TestModel
    success_url = reverse_lazy("testapp:testmodels")
    title = "Delete Test"

testapp/templates/testapp/settings.html
{{ TIME_ZONE }}

testapp/templates/testapp/testmodel.html
  <tr>
    <td>{{ object.get_link }}</td>
    <td>{{ object.slug }}</td>
    <td>{{ object.created }}</td>
    <td>{{ object.updated }}</td>
    <td>{{ object.get_year_in_school_display }}</td>
    <td>{{ object.tests }}</td>
    <td>{{ object.moment }}</td>
    <td><a href="{% url 'testapp:testmodel-update' object.slug %}">update</a></td>
    <td><a href="{% url 'testapp:testmodel-delete' object.slug %}">delete</a></td>
  </tr>

testapp/templates/testapp/testmodel_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/delete.html' %}
{% endblock %}

testapp/templates/testapp/testmodel_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ object }}</h1>

<table class="table">

  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>Created</th>
    <th>Updated</th>
    <th>Year in School</th>
    <th>Tests</th>
    <th>Moment</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>
  {% include 'testapp/testmodel.html' with object=object %}
</table>
{% endblock %}

testapp/templates/testapp/testmodel_form.html
{% extends 'base.html' %}

{% block content %}
{% include 'ndh/form.html' %}
{% endblock %}

testapp/templates/testapp/testmodel_list.html
{% extends 'base.html' %}

{% block content %}
<h1>TestModels</h1>

<table class="table">

  <tr>
    <th>Name</th>
    <th>Slug</th>
    <th>Created</th>
    <th>Updated</th>
    <th>Year in School</th>
    <th>Tests</th>
    <th>Moment</th>
    <th>Update</th>
    <th>Delete</th>
  </tr>

  {% for object in object_list %}
  {% include 'testapp/testmodel.html' with object=object %}
  {% endfor %}
</table>
{% endblock %}